{{ if .Values.ingress }}
{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.application_name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.application_name }}
  {{- if or .Values.ingress.annotations .Values.ingress.tls }}
  annotations:
    {{- if .Values.ingress.caIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.caIssuer | quote }}
    cert-manager.io/common-name: {{ .Values.ingress.dns | quote }}
    {{- end}}
  {{- with .Values.ingress.annotations }}
  {{- toYaml . | nindent 4  }}
  {{- end }}
  {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.dns }}
      secretName: {{ .Values.ingress.dns }}-tls
  {{- end}}
  rules:
    - host: {{ .Values.ingress.dns }}
      http:
        paths:
          {{- $root := . -}}
          {{ range .Values.ingress.paths }}
          - path: {{ .path  }}
            pathType: {{ coalesce .pathType "Prefix" | quote }}
            backend:
              service:
                name: {{ $root.Values.application_name }}
                port:
                  number: {{ $root.Values.service.port }}
          {{- end }}
{{ end }}
{{ end }}
